### ISSUE TITLE
Rails 2.3 compatibility. 

### ISSUE THREAD

**Issue by mariozaizar** [kelyar/mailer_callbacks#1]
Hi, I'm wondering how you feel about using this gem in production environments. Specifically with Rails 2.3.
I require some sort of before_filters or mail_interceptors for ActionMailer. Any help on that will be really appreciated. 

Thanks

**Comment by kelyar** [comment]
Hi Mario,

It definitely won't work with 3.x, but I believe it should work with 2.3.
The code is tiny and dead simple, so it should be easy to check.

Good luck! )

**Comment by inspire22** [comment]
Any tips or ideas for rails 3.x?

**Comment by mariozaizar** [comment]
@inspire22 Sorry, I didn't dig into this anymore. I started implementing a different mailer using sidekiq async queue and a 3rd party email provider.

**Comment by kelyar** [comment]
@inspire22 There is a 2.0 branch that is rails3 compatible. https://github.com/kelyar/mailer_callbacks/tree/2.0

It works almost the same, but api slighly changed. Just ping me if you need any details.
